const sources={sepe:{label:"Perfiles profesionales · SEPE",url:"https://www.sepe.es/HomeSepe/que-es-observatorio/perfiles-de-la-oferta-de-empleo/Perfiles-profesionales.html"},needs:{label:"Necesidades formativas · SEPE",url:"https://www.sepe.es/HomeSepe/que-es-observatorio/deteccion-necesidades-formativas/buscador-necesidades-formativas.html"},fp:{label:"Catálogos y registros · TodoFP",url:"https://www.todofp.es/catalogos-registros-sistema-fp.html"}};
// Selección editorial ilustrativa. Rutas y habilidades requieren revisión individual antes de uso institucional.
const jobs=[
 {id:"enfermeria",name:"Enfermería",sector:"Salud",icon:"✚",summary:"Cuidar, acompañar y tomar decisiones clínicas junto a un equipo.",tasks:["Atender y observar la evolución de pacientes","Coordinar cuidados con otros profesionales","Educar en prevención y autocuidado"],skills:["Comunicación empática","Conocimiento clínico","Trabajo en equipo"],routes:["Grado universitario en Enfermería","Consultar requisitos de acceso, colegiación y ejercicio profesional vigentes"],regulated:true,stage:["eso","bach","adulto"],src:["sepe"]},
 {id:"electricidad",name:"Electricista",sector:"Industria y energía",icon:"⚡",summary:"Instalar y mantener sistemas eléctricos con seguridad.",tasks:["Montar instalaciones y equipos","Detectar y reparar averías","Aplicar protocolos de seguridad"],skills:["Interpretación de planos","Diagnóstico técnico","Seguridad laboral"],routes:["FP de la familia Electricidad y Electrónica","Certificados o acreditaciones aplicables según la actividad"],stage:["eso","fp","adulto"],src:["fp","needs"]},
 {id:"educacion",name:"Docencia de primaria",sector:"Educación",icon:"◈",summary:"Diseñar aprendizajes y acompañar el desarrollo de niños y niñas.",tasks:["Preparar actividades de aprendizaje","Evaluar y apoyar necesidades diversas","Colaborar con familias y centro"],skills:["Didáctica","Comunicación","Planificación"],routes:["Grado universitario en Educación Primaria","Revisar requisitos de habilitación y acceso según centro y comunidad"],regulated:true,stage:["eso","bach","adulto"],src:["sepe"]},
 {id:"cocina",name:"Cocina profesional",sector:"Hostelería",icon:"◒",summary:"Transformar ingredientes en experiencias, organizando tiempos y equipos.",tasks:["Preparar platos y menús","Organizar producción y suministros","Cuidar higiene y seguridad alimentaria"],skills:["Técnicas culinarias","Organización","Trabajo bajo presión"],routes:["FP de la familia Hostelería y Turismo","Formación práctica y otras vías de especialización"],stage:["eso","fp","adulto"],src:["fp","needs"]},
 {id:"trabajo-social",name:"Trabajo social",sector:"Social y comunidad",icon:"♡",summary:"Acompañar a personas y comunidades para acceder a recursos y derechos.",tasks:["Evaluar necesidades sociales","Orientar y coordinar recursos","Diseñar intervenciones con personas y equipos"],skills:["Escucha activa","Conocimiento de recursos","Mediación"],routes:["Grado universitario en Trabajo Social","Comprobar requisitos profesionales y convocatorias para empleo público"],regulated:true,stage:["eso","bach","adulto"],src:["sepe"]},
 {id:"logistica",name:"Logística y transporte",sector:"Comercio y logística",icon:"▣",summary:"Conseguir que productos y materiales lleguen donde hacen falta.",tasks:["Planificar flujos y entregas","Gestionar almacenes e inventarios","Resolver incidencias operativas"],skills:["Planificación","Herramientas de gestión","Coordinación"],routes:["FP de la familia Comercio y Marketing","Formación especializada y experiencia operativa"],stage:["eso","fp","adulto"],src:["fp","sepe"]},
 {id:"desarrollo",name:"Desarrollo de software",sector:"Tecnología",icon:"⌘",summary:"Construir herramientas digitales que resuelven problemas reales.",tasks:["Diseñar y programar aplicaciones","Probar y mantener sistemas","Colaborar con diseño y usuarios"],skills:["Programación","Resolución de problemas","Trabajo colaborativo"],routes:["FP de la familia Informática y Comunicaciones","Grados universitarios relacionados u otras vías demostrables"],stage:["eso","bach","fp","adulto"],src:["fp","sepe"]},
 {id:"ambiental",name:"Educación ambiental",sector:"Medioambiente",icon:"❋",summary:"Ayudar a comprender y cuidar los ecosistemas y el territorio.",tasks:["Diseñar actividades educativas","Explicar impactos ambientales","Coordinar proyectos con comunidades"],skills:["Divulgación","Conocimiento ambiental","Diseño de actividades"],routes:["FP y grados vinculados al medioambiente o educación","Especialización y experiencia en proyectos"],stage:["eso","bach","fp","adulto"],src:["fp","needs"]},
 {id:"administracion",name:"Administración y gestión",sector:"Servicios y empresa",icon:"▤",summary:"Organizar procesos, documentación y atención para que una entidad funcione.",tasks:["Gestionar documentación y trámites","Atender consultas y coordinar tareas","Controlar plazos e información"],skills:["Organización","Herramientas digitales","Atención a personas"],routes:["FP de la familia Administración y Gestión","Otros estudios relacionados y experiencia según puesto"],stage:["eso","fp","adulto"],src:["fp","sepe"]},
 {id:"agricultura",name:"Producción agraria",sector:"Campo y alimentación",icon:"☘",summary:"Trabajar con cultivos, recursos y tecnología para producir alimentos.",tasks:["Planificar y cuidar cultivos","Operar equipos y sistemas de riego","Aplicar prácticas de seguridad y sostenibilidad"],skills:["Conocimiento de cultivos","Manejo de equipos","Observación"],routes:["FP de la familia Agraria","Formación práctica y acreditaciones según actividad"],stage:["eso","fp","adulto"],src:["fp","needs"]}
];
